# Generated by Django 5.0.1 on 2024-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
